### PR TITLE
add Vagrantfile; also serves as working example for configuring a server

### PR DESCRIPTION
**Pull request by MihaiB**
Also configure Sphinx search locally and increase VM RAM size to 2.5 GB
because IsoHunt's remote Sphinx server is down at the moment (Jan 2015).
This can be commented out when that server comes back up, but it will
still serve as a concrete working example for Sphinx configuration.

### CODE REVIEW

**Comment by jalcine** [comment]
Runs well on Linux box (running Trusty as well).

**Comment by DaveBlooman** [comment]
Getting errors on vagrant up

```sh
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: sphinxsearch stop/waiting
==> default: Traceback (most recent call last):
==> default:   File "/vagrant/vagrant/sphinx_passwords.py", line 19, in <module>
==> default:     data = json.loads(f.read().decode('utf-8'))
==> default:   File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
==> default:     return _default_decoder.decode(s)
==> default:   File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
==> default:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
==> default:   File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
==> default:     raise ValueError(errmsg("Expecting value", s, err.value)) from None
==> default: ValueError: Expecting value: line 1 column 1 (char 0)
==> default: /vagrant/vagrant/sphinx.sh failed because a command in the script failed
==> default: /tmp/vagrant-shell failed because a command in the script failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by MihaiB** [comment]
Works for me – just tested again on a clean checkout.
@DaveBlooman, looks like the script got an empty response from http://isohunt.to/openbay/config.json
Do you see some json data if you open that URL in your browser (to check that your network doesn't block it)?
If yes, destroy the vm, get a clean checkout and try another `vagrant up` (that site might have been temporarily down)?

**Comment by TomSeldon** [comment]
I had the same issue as @DaveBlooman, until I connected to a VPN and re-created the VM. (Just re-provisioning didn't work). The above file was being blocked.

**Comment by jalcine** [comment]
Do you guys get this issue when attempting to directly `curl` the file?

**Comment by DaveBlooman** [comment]
@TomSeldon Thanks, looks like BT has an issue here.

**Pull request closed without merging**
